copyright: Copyright (c) FM
repo_url: https://github.com/francmarx/testFM
site_description: Test MkDocs
site_name: Testerei
#site_url: https://docs.mainflux.io
edit_uri: ""
theme:
  name: material
#  logo: img/logo.png
#  favicon: img/logo.png
#  icon:
#    repo: fontawesome/brands/github

markdown_extensions:
  - admonition
  - toc:
      permalink: "#"

nav:
  - Overview: index.md
  
